### ISSUE TITLE
Transfer Maven repo

### ISSUE THREAD

**Issue by nightscape** [xencura/kagera#139]
Hi @nikolakasev,

I've contacted the friendly people at Sonatype to transfer the ownership of the Kagera Maven repo over to me. They can do that if the original owner of the repo comments his agreement on the corresponding JIRA issue here:
https://issues.sonatype.org/browse/OSSRH-72370

Unfortunately we have lost the issue history during the GitHub repository transfer, so I have lost the conversation where you mentioned your (ex-?) colleague who owns the Maven repo.

Would you be so kind to mention him here, or make him aware of this issue on any other communication channel?

Thanks a lot!
Martin

**Comment by merlijn** [comment]
@nightscape Hi there. I am the original creator of the kagera repo. I also commented on your sonatype ticket. This all happened because I deleted my original repo. I never thought anyone would use it since the project was a bit immature honestly and all the code was later merged into the ing-bank/baker project.

Anyway, excuse me for the hold up. Like I mentioned on the sonatype ticket I do have plans for the io.kagera domain for another project so I hope you don't mind doing a name change. Technically that should be super easy of course but maybe you have become attached to the kagera name? Sorry about that.

Btw, what are your plans with the project? I'd love to know since petri nets still sort of have an interest to me.

**Comment by nightscape** [comment]
Hey @merlijn, great timing and thanks for getting back!
I actually found ing-bank/baker first, but it's combining things in a way that makes it not usable for our case.
I then stumbled upon kagera and liked that it has more of a "library approach" than the "framework approach" of baker.
Petri Nets play a rather big part for Xencura (a personalized cancer medicine startup I'm involved with) so hopefully this library will continue to grow, and maybe one day even form the library basis of the banker framework. Who knows 🤷 😃 .

I'm not attached to the name in any way and as we seem to be the only users, a rename shouldn't hurt.
I'll probably give it a more boring name containing `petri net` and `scala` in some combination 😉 

Thanks again for checking in and commenting here and on the Sonatype JIRA!

**Comment by merlijn** [comment]
@nightscape 
Yes, petri nets are a solid base for process orchestration. A lightweight, library-first approach was the idea for Kagera but in the end it was just unworkable to keep it separate from baker.

I do actually like *very much* the Recipe DSL that we put on top of petri nets in baker. This was largely an idea from Nikola. It makes sense for most business processes and is more easily understandable and I am sure there are more use cases. 

For some cases however, like yours probably, the more low level petri nets are better. 

Also, ING is a large company so Baker naturally became more "framework like". This actually makes sense in that environment. It is actually quite light compared to other stuff that is used over there. The separation between petri-net stuff and recipe stuff is unfortunately completely gone and you can no longer use it as a pure petri-net library. It would be nice to have that restored. Anyway I am no longer involved in baker since almost 3 years now.

FYI, an ex colleague of mine started [statebox](https://statebox.org/). This is yet another approach to petri nets, more academic. Probably not usable for your purposes but still interesting.

I wish you good luck with your library!
